"""empty message

Revision ID: f041c567d957
Revises: fe7222b27e46
Create Date: 2017-07-09 22:25:07.398339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f041c567d957'
down_revision = 'fe7222b27e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlistitems_created_by_fkey', 'bucketlistitems', type_='foreignkey')
    op.drop_column('bucketlistitems', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistitems', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bucketlistitems_created_by_fkey', 'bucketlistitems', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###
