"""empty message

Revision ID: fe7222b27e46
Revises: 3be4ca163b7e
Create Date: 2017-07-09 22:22:16.388459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7222b27e46'
down_revision = '3be4ca163b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistitems', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bucketlistitems', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlistitems', type_='foreignkey')
    op.drop_column('bucketlistitems', 'created_by')
    # ### end Alembic commands ###
